### PR TITLE
fix(select): fixed a bug where the option group `builder` property was not being called

### LINKED ISSUE #260: [select] option group `builder` not being called
**Describe the bug:**
The `builder` callback on the `ISelectOptionGroup` objects when applied to the `<forge-select>` is not being called.

The issue is located here:
https://github.com/tyler-technologies-oss/forge/blob/main/src/lib/select/core/base-select-adapter.ts#L228

Another issue is that you can't bind a `builder` property to the `<forge-option-group>` elements because it doesn't exist on the public API and therefore you are required to set the options via the `options` property on the `<forge-select>`. We need to make sure that the `<forge-option-group>` element implements the `ISelectOptionGroup` interface to ensure the same properties can be used declaratively.

**To Reproduce:**
View the StackBlitz example here:
https://stackblitz.com/edit/forge-select-with-groups

**Expected behavior:**
The `builder` callback should be executed when set imperatively via the `options` property on the `<forge-select>`, or when used declaratively via the `<forge-option-group>` element (which will be generated if using the imperative approach anyway). 

**Please complete the following information:**
 - Forge version: ^2.00
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Additional context:**
We should validate all other properties are usable, updated any unit tests, and that the `<forge-option>` element operates as expected as well.

### PR DESCRIPTION
**Pull request by DRiFTy17**
## PR Checklist

Please check if your PR fulfills the following requirements:

- Tests for the changes have been added: Y
- Docs have been added / updated: N
- Does this PR introduce a breaking change? N
- I have linked any related GitHub issues to be closed when this PR is merged? Y

## Describe the new behavior?
The `builder` property on `<forge-option-group>` elements (among other properties) will now correctly propagate to the list-dropdown.

## Additional information
Fixes #260

### CODE REVIEW

File: src/lib/select/core/base-select-adapter.ts [hunk 1]
```diff
@@ -64,7 +63,11 @@ export abstract class BaseSelectAdapter extends BaseAdapter<IBaseSelectComponent
       return optionGroupElements.map(optionGroupElement => {
         const optionElements = Array.from(optionGroupElement.querySelectorAll(OPTION_CONSTANTS.elementName)) as IOptionComponent[];
         const options = this._createOptionsFromElements(optionElements);
-        return { text: optionGroupElement.label, options } as ISelectOptionGroup;
+        return {
+          text: optionGroupElement.label,
+          builder: optionGroupElement.builder,
```
Comment (DRiFTy17) [inline src/lib/select/core/base-select-adapter.ts:68]: The `builder` property missing from here was the main problem.

File: src/lib/select/core/base-select-adapter.ts [hunk 2]
```diff
@@ -225,14 +228,13 @@ export abstract class BaseSelectAdapter extends BaseAdapter<IBaseSelectComponent
 
   private _createOptionGroupElement(group: ISelectOptionGroup): HTMLElement {
     const optionGroupElement = document.createElement('forge-option-group');
-    assignMatchingProperties(group, optionGroupElement);
-    optionGroupElement.label = group.text ?? '';
+    Object.assign(optionGroupElement, group);
```
Comment (DRiFTy17) [inline src/lib/select/core/base-select-adapter.ts:231]: We will now just blindly copy everything from the config objects for both options and option groups. The previous strategy of only applying "matching properties" was short sighted.

File: src/lib/select/core/select-utils.ts [hunk 3]
```diff
@@ -15,7 +15,7 @@ export function isSelectOptionType(options: ISelectOption[] | ISelectOptionGroup
 }
 
 export function isOptionGroupObject(o: ISelectOption | ISelectOptionGroup): o is ISelectOptionGroup {
-  return isDefined(o) && isObject(o) && o.hasOwnProperty('options') && o.hasOwnProperty('text');
+  return isDefined(o) && isObject(o) && o.hasOwnProperty('options');
```
Comment (DRiFTy17) [inline src/lib/select/core/select-utils.ts:18]: We do not need to ensure that the `text` property is provided since the existing of the `options` property is all we actually care about to determine if this is an option group.

File: src/lib/select/option-group/option-group.ts [hunk 4]
```diff
@@ -51,4 +53,18 @@ export class OptionGroupComponent extends BaseComponent implements IOptionGroupC
...
+  /** The builder function for the group content. */
+  public declare builder: ListDropdownOptionGroupBuilder;
+
+  /** The text content for the group. */
+  public get text(): string {
+    return this._label;
+  }
+  public set text(value: string) {
+    this.label = value;
+  }
```
Comment (DRiFTy17) [inline src/lib/select/option-group/option-group.ts:69]: These properties can be set on the `<forge-option-group>` elements instead of forcing it to be done through JavaScript only.

**Review by samrichardsontylertech — APPROVED** [review]
